name: flutter_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.7.0-0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  progress_dialog:
  stripe_payment:
  timeago:
  get:
  get_storage:
  cached_network_image:
  http:
  uuid:
  shared_preferences:
  country_list_pick:
  flutter_datetime_picker: ^1.4.0
  loading_animations:
  bot_toast:
  geolocator: 6.1.8
  geocoding: ^1.0.5
  curved_navigation_bar:
  animated_splash_screen: ^1.0.1+2
  auto_size_text: ^2.1.0
  fswitch: ^1.1.2
  sliding_up_panel:
  cupertino_icons: ^0.1.3
  google_maps_flutter: ^1.0.6
  animations:
  credit_card: 0.1.6
  font_awesome_flutter:
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - assets/images/facebook.png
    - assets/images/email.png
    - assets/images/google.png
    - assets/images/MaskGroup1.png
    - assets/images/plus.png
    - assets/images/minus.png
    - assets/images/Icon_Delete.png
    - assets/images/foodImg.png
    - assets/images/icons-back.png
    - assets/images/bag.png
    - assets/images/ic_wishlist.png
    - assets/images/location.png
    - assets/images/drop.png
    - assets/images/bell.png
    - assets/images/editProfile.png
    - assets/images/orderHistory.png
    - assets/images/Notifications.png
    - assets/images/Wishlist.png
    - assets/images/logOut.png
    - assets/images/heart_circ_clicked.png
    - assets/images/heart_circ_grey.png
    - assets/images/compass.png
    - assets/images/cart.png
    - assets/images/foodImg2.png
    - assets/images/back.png
    - assets/images/back1.png
    - assets/images/foodImgRound.png
    - assets/images/customMarker.png
    - assets/images/customFoodMarker.png
    - assets/images/map_pin.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
